CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "UserType" integer NOT NULL,
        "CompanyName" text,
        "BusinessRegistrationNumber" text,
        "RegistrationDate" timestamp with time zone NOT NULL,
        "LastLogin" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(255) NOT NULL,
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "ParentCategoryId" integer,
        "Description" text,
        "DisplayOrder" integer NOT NULL,
        "ImageUrl" text,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "MarketPrices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaterialName" text NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "UnitOfMeasure" text NOT NULL,
        "Currency" text NOT NULL,
        "LastUpdated" timestamp with time zone NOT NULL,
        "Source" text,
        CONSTRAINT "PK_MarketPrices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "SEOMetadata" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PageName" text NOT NULL,
        "PageTitle" text,
        "MetaDescription" text,
        "MetaKeywords" text,
        "PageUrl" text,
        "PageOrder" integer,
        "LastUpdated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SEOMetadata" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "Addresses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "AddressLine1" text NOT NULL,
        "AddressLine2" text,
        "City" text NOT NULL,
        "StateProvince" text NOT NULL,
        "PostalCode" text NOT NULL,
        "Country" text NOT NULL,
        "AddressType" integer NOT NULL,
        CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Addresses_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" integer NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "ShoppingCarts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SessionId" text NOT NULL,
        "UserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ShoppingCarts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShoppingCarts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "Tenders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer,
        "GuestName" text,
        "GuestEmail" text,
        "GuestPhone" text,
        "GuestCompany" text,
        "GuestCity" text,
        "TenderTitle" text NOT NULL,
        "TenderDescription" text,
        "RequestDate" timestamp with time zone NOT NULL,
        "SubmissionDeadline" timestamp with time zone,
        "RequiredDeliveryDate" timestamp with time zone,
        "Status" integer NOT NULL,
        "AwardedSupplierId" integer,
        "TotalQuotedAmount" numeric(18,2),
        "Notes" text,
        "NegotiationNotes" text,
        CONSTRAINT "PK_Tenders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tenders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "CategoryId" integer NOT NULL,
        "SupplierId" integer,
        "RetailPrice" numeric(18,2) NOT NULL,
        "UnitOfMeasure" text NOT NULL,
        "StockQuantity" integer NOT NULL,
        "Sku" text NOT NULL,
        "Weight" numeric(18,2),
        "Dimensions" text,
        "ImageUrl" text,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "BulkPricingAvailable" boolean NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderNumber" text NOT NULL,
        "UserId" integer NOT NULL,
        "OrderDate" timestamp with time zone NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Status" integer NOT NULL,
        "ShippingAddressId" integer NOT NULL,
        "BillingAddressId" integer NOT NULL,
        "PaymentMethod" text,
        "PaymentStatus" text,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Addresses_BillingAddressId" FOREIGN KEY ("BillingAddressId") REFERENCES "Addresses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_Addresses_ShippingAddressId" FOREIGN KEY ("ShippingAddressId") REFERENCES "Addresses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "Projects" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ProjectName" text NOT NULL,
        "Description" text,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "LocationAddressId" integer,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Projects_Addresses_LocationAddressId" FOREIGN KEY ("LocationAddressId") REFERENCES "Addresses" ("Id"),
        CONSTRAINT "FK_Projects_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "ProductImages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "Url" text NOT NULL,
        "AltText" text,
        "Caption" text,
        "DisplayOrder" integer NOT NULL,
        CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "ShoppingCartItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ShoppingCartId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "AddedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ShoppingCartItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShoppingCartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ShoppingCartItems_ShoppingCarts_ShoppingCartId" FOREIGN KEY ("ShoppingCartId") REFERENCES "ShoppingCarts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "TenderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenderId" integer NOT NULL,
        "ProductId" integer,
        "ProductName" text,
        "Unit" text,
        "RequestedQuantity" numeric(18,2) NOT NULL,
        "ProposedPricePerUnit" numeric(18,2),
        "TargetPricePerUnit" numeric(18,2),
        "SubtotalItem" numeric(18,2),
        CONSTRAINT "PK_TenderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TenderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id"),
        CONSTRAINT "FK_TenderItems_Tenders_TenderId" FOREIGN KEY ("TenderId") REFERENCES "Tenders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "Subtotal" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Orders_BillingAddressId" ON "Orders" ("BillingAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Orders_ShippingAddressId" ON "Orders" ("ShippingAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Projects_LocationAddressId" ON "Projects" ("LocationAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Projects_UserId" ON "Projects" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_ShoppingCartItems_ProductId" ON "ShoppingCartItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_ShoppingCartItems_ShoppingCartId" ON "ShoppingCartItems" ("ShoppingCartId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_ShoppingCarts_UserId" ON "ShoppingCarts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_TenderItems_ProductId" ON "TenderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_TenderItems_TenderId" ON "TenderItems" ("TenderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    CREATE INDEX "IX_Tenders_UserId" ON "Tenders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260621011326_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260621011326_InitialPostgres', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623175820_AddMustChangePasswordToUser') THEN
    ALTER TABLE "AspNetUsers" ADD "MustChangePassword" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260623175820_AddMustChangePasswordToUser') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260623175820_AddMustChangePasswordToUser', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626140634_AddBrandAndCountryOfOriginToProduct') THEN
    ALTER TABLE "Products" ADD "Brand" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626140634_AddBrandAndCountryOfOriginToProduct') THEN
    ALTER TABLE "Products" ADD "CountryOfOrigin" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260626140634_AddBrandAndCountryOfOriginToProduct') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260626140634_AddBrandAndCountryOfOriginToProduct', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710203239_AddAppSettingsTable') THEN
    CREATE TABLE "AppSettings" (
        "Key" character varying(100) NOT NULL,
        "Value" text NOT NULL,
        "Description" text,
        "LastUpdated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AppSettings" PRIMARY KEY ("Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710203239_AddAppSettingsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260710203239_AddAppSettingsTable', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710210329_AddShippingRatesTable') THEN
    CREATE TABLE "ShippingRates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CityName" character varying(100) NOT NULL,
        "Rate" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_ShippingRates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710210329_AddShippingRatesTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260710210329_AddShippingRatesTable', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    ALTER TABLE "Orders" ADD "AppliedCouponCode" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    ALTER TABLE "Orders" ADD "DiscountAmount" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE TABLE "Coupons" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(50) NOT NULL,
        "DiscountType" text NOT NULL,
        "DiscountValue" numeric(18,2) NOT NULL,
        "ExpiryDate" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "UsageCount" integer NOT NULL,
        CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE TABLE "DeliveryCompanies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Email" text,
        "PhoneNumber" text,
        "CommercialRegister" text,
        "BaseDeliveryRate" numeric(18,2) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_DeliveryCompanies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE TABLE "DeliveryDrivers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "DeliveryCompanyId" integer,
        "VehicleType" text,
        "VehiclePlateNumber" text,
        "LicenseNumber" text,
        "IsAvailable" boolean NOT NULL,
        "IsApproved" boolean NOT NULL,
        "AverageRating" numeric(18,2) NOT NULL,
        "TotalRatings" integer NOT NULL,
        CONSTRAINT "PK_DeliveryDrivers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DeliveryDrivers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_DeliveryDrivers_DeliveryCompanies_DeliveryCompanyId" FOREIGN KEY ("DeliveryCompanyId") REFERENCES "DeliveryCompanies" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE TABLE "DeliveryJobs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "DriverId" integer,
        "Status" integer NOT NULL,
        "DeliveryFee" numeric(18,2) NOT NULL,
        "PickupLocation" text NOT NULL,
        "DropoffLocation" text NOT NULL,
        "AssignedAt" timestamp with time zone,
        "PickedUpAt" timestamp with time zone,
        "DeliveredAt" timestamp with time zone,
        CONSTRAINT "PK_DeliveryJobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DeliveryJobs_DeliveryDrivers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "DeliveryDrivers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_DeliveryJobs_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE TABLE "DeliveryBids" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DeliveryJobId" integer NOT NULL,
        "DriverId" integer NOT NULL,
        "BidAmount" numeric(18,2) NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DeliveryBids" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DeliveryBids_DeliveryDrivers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "DeliveryDrivers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DeliveryBids_DeliveryJobs_DeliveryJobId" FOREIGN KEY ("DeliveryJobId") REFERENCES "DeliveryJobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE TABLE "DeliveryRatings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DeliveryJobId" integer NOT NULL,
        "DriverId" integer NOT NULL,
        "CustomerId" integer NOT NULL,
        "RatingValue" integer NOT NULL,
        "Comment" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DeliveryRatings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DeliveryRatings_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DeliveryRatings_DeliveryDrivers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "DeliveryDrivers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DeliveryRatings_DeliveryJobs_DeliveryJobId" FOREIGN KEY ("DeliveryJobId") REFERENCES "DeliveryJobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryBids_DeliveryJobId" ON "DeliveryBids" ("DeliveryJobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryBids_DriverId" ON "DeliveryBids" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryDrivers_DeliveryCompanyId" ON "DeliveryDrivers" ("DeliveryCompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryDrivers_UserId" ON "DeliveryDrivers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryJobs_DriverId" ON "DeliveryJobs" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryJobs_OrderId" ON "DeliveryJobs" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryRatings_CustomerId" ON "DeliveryRatings" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE UNIQUE INDEX "IX_DeliveryRatings_DeliveryJobId" ON "DeliveryRatings" ("DeliveryJobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    CREATE INDEX "IX_DeliveryRatings_DriverId" ON "DeliveryRatings" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260710212113_AddDeliverySystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260710212113_AddDeliverySystem', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711133830_AddNotificationTable') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer,
        "Title" text NOT NULL,
        "Message" text NOT NULL,
        "ActionUrl" text,
        "IsRead" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711133830_AddNotificationTable') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711133830_AddNotificationTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711133830_AddNotificationTable', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    ALTER TABLE "DeliveryJobs" ADD "CollectedAmount" numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    ALTER TABLE "DeliveryJobs" ADD "DeliveryCompanyId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    ALTER TABLE "DeliveryJobs" ADD "IsReconciled" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    ALTER TABLE "DeliveryJobs" ADD "ReconciledAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    ALTER TABLE "DeliveryJobs" ADD "ReturnReason" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    ALTER TABLE "DeliveryCompanies" ADD "ManagerUserId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    CREATE INDEX "IX_DeliveryJobs_DeliveryCompanyId" ON "DeliveryJobs" ("DeliveryCompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    ALTER TABLE "DeliveryJobs" ADD CONSTRAINT "FK_DeliveryJobs_DeliveryCompanies_DeliveryCompanyId" FOREIGN KEY ("DeliveryCompanyId") REFERENCES "DeliveryCompanies" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260711215542_AddDeliveryReconciliation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260711215542_AddDeliveryReconciliation', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717045637_AddEnglishTranslationsColumns') THEN
    ALTER TABLE "Products" ADD "DescriptionEn" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717045637_AddEnglishTranslationsColumns') THEN
    ALTER TABLE "Products" ADD "NameEn" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717045637_AddEnglishTranslationsColumns') THEN
    ALTER TABLE "DeliveryJobs" ADD "DeliveryToken" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717045637_AddEnglishTranslationsColumns') THEN
    ALTER TABLE "Categories" ADD "DescriptionEn" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717045637_AddEnglishTranslationsColumns') THEN
    ALTER TABLE "Categories" ADD "NameEn" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717045637_AddEnglishTranslationsColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260717045637_AddEnglishTranslationsColumns', '8.0.11');
    END IF;
END $EF$;
COMMIT;

