using Microsoft.AspNetCore.SignalR;
using System.Security.Claims;

namespace Bolcko.Web.App.Hubs
{
    public class CustomUserIdProvider : IUserIdProvider
    {
        public string? GetUserId(HubConnectionContext connection)
        {
            var user = connection.User;
            if (user == null) return null;

            // 1. Try NameIdentifier claim (standard SOAP claim type for cookies)
            var claim = user.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null) return claim.Value;

            // 2. Try nameid claim (JWT claim generated by TokenService)
            claim = user.FindFirst("nameid");
            if (claim != null) return claim.Value;

            // 3. Try sub claim (standard OpenID/JWT subject)
            claim = user.FindFirst("sub");
            if (claim != null) return claim.Value;

            // 4. Try Name claim as a fallback
            claim = user.FindFirst(ClaimTypes.Name);
            if (claim != null) return claim.Value;

            return null;
        }
    }
}
