using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blocko.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddSupplierIntegrationAndSourcingToOrder : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent SQL commands for PostgreSQL to safely apply changes without crashing if columns exist
            migrationBuilder.Sql(@"
                ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""ExternalSupplierVariantId"" integer;
                ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""SupplierKey"" text;

                ALTER TABLE ""Orders"" ADD COLUMN IF NOT EXISTS ""ExternalSupplierOrderNumber"" text;
                ALTER TABLE ""Orders"" ADD COLUMN IF NOT EXISTS ""PrimarySupplierKey"" text;
                ALTER TABLE ""Orders"" ADD COLUMN IF NOT EXISTS ""SourcingNotes"" text;
                ALTER TABLE ""Orders"" ADD COLUMN IF NOT EXISTS ""SourcingStatus"" integer NOT NULL DEFAULT 0;

                ALTER TABLE ""OrderItems"" ADD COLUMN IF NOT EXISTS ""ExternalSupplierOrderId"" text;
                ALTER TABLE ""OrderItems"" ADD COLUMN IF NOT EXISTS ""ExternalSupplierVariantId"" integer;
                ALTER TABLE ""OrderItems"" ADD COLUMN IF NOT EXISTS ""SourcingNotes"" text;
                ALTER TABLE ""OrderItems"" ADD COLUMN IF NOT EXISTS ""SourcingStatus"" integer NOT NULL DEFAULT 0;
                ALTER TABLE ""OrderItems"" ADD COLUMN IF NOT EXISTS ""SupplierKey"" text;

                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""ChangePercent"" double precision NOT NULL DEFAULT 0.0;
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""CityRatesJson"" text;
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""GlobalPriceUsd"" numeric;
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""IsLiveAutoUpdated"" boolean NOT NULL DEFAULT false;
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""MaterialCategory"" text NOT NULL DEFAULT '';
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""MaterialNameEn"" text;
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""PreviousPrice"" numeric;
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""Specification"" text;
                ALTER TABLE ""MarketPrices"" ADD COLUMN IF NOT EXISTS ""Trend"" text NOT NULL DEFAULT '';

                CREATE TABLE IF NOT EXISTS ""FAQItems"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""QuestionAr"" text NOT NULL,
                    ""AnswerAr"" text NOT NULL,
                    ""QuestionEn"" text,
                    ""AnswerEn"" text,
                    ""PageTarget"" text NOT NULL,
                    ""DisplayOrder"" integer NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS ""SupplierProviderConfigs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""SupplierName"" text NOT NULL,
                    ""SupplierKey"" text NOT NULL,
                    ""BaseUrl"" text NOT NULL,
                    ""ApiPhoneNumber"" text,
                    ""ApiPassword"" text,
                    ""ApiEmail"" text,
                    ""AuthToken"" text,
                    ""ExternalCustomerId"" integer,
                    ""ExternalUserId"" integer,
                    ""PickupAddressLine"" text,
                    ""PickupCityId"" bigint NOT NULL,
                    ""PickupRegionId"" bigint NOT NULL,
                    ""PickupVillageId"" bigint NOT NULL,
                    ""ContactPersonName"" text,
                    ""ContactPhoneNumber"" text,
                    ""AutoDispatchEnabled"" boolean NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CustomHeadersJson"" text,
                    ""CustomPayloadMappingJson"" text,
                    ""Notes"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SupplierProviderConfigs");

            migrationBuilder.DropColumn(
                name: "ExternalSupplierVariantId",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "SupplierKey",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "ExternalSupplierOrderNumber",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "PrimarySupplierKey",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "SourcingNotes",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "SourcingStatus",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "ExternalSupplierOrderId",
                table: "OrderItems");

            migrationBuilder.DropColumn(
                name: "ExternalSupplierVariantId",
                table: "OrderItems");

            migrationBuilder.DropColumn(
                name: "SourcingNotes",
                table: "OrderItems");

            migrationBuilder.DropColumn(
                name: "SourcingStatus",
                table: "OrderItems");

            migrationBuilder.DropColumn(
                name: "SupplierKey",
                table: "OrderItems");
        }
    }
}
