using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blocko.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class addoversizedprodctColmun : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""IsOversized"" boolean NOT NULL DEFAULT FALSE;");
            migrationBuilder.Sql(@"ALTER TABLE ""Addresses"" ADD COLUMN IF NOT EXISTS ""Latitude"" double precision NULL;");
            migrationBuilder.Sql(@"ALTER TABLE ""Addresses"" ADD COLUMN IF NOT EXISTS ""Longitude"" double precision NULL;");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""DeliveryProviderConfigs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ProviderName"" text NOT NULL,
                    ""ProviderKey"" text NOT NULL,
                    ""BaseUrl"" text NOT NULL,
                    ""CompanyId"" text NOT NULL,
                    ""ApiEmail"" text NOT NULL,
                    ""ApiPassword"" text NOT NULL,
                    ""WebhookSecret"" text,
                    ""OutboundWebhookUrl"" text,
                    ""CustomHeadersJson"" text,
                    ""CustomPayloadMappingJson"" text,
                    ""IsActive"" boolean NOT NULL DEFAULT FALSE,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (now()),
                    ""UpdatedAt"" timestamp with time zone
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""DeliveryProviderLocationMappings"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ProviderKey"" text NOT NULL,
                    ""SearchName"" text NOT NULL,
                    ""NormalizedSearchName"" text,
                    ""ExternalCityId"" bigint NOT NULL,
                    ""ExternalCityName"" text,
                    ""ExternalRegionId"" bigint NOT NULL,
                    ""ExternalRegionName"" text,
                    ""ExternalVillageId"" bigint NOT NULL,
                    ""ExternalVillageName"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (now())
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""OrderShipmentMappings"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""OrderId"" integer NOT NULL,
                    ""ProviderKey"" text NOT NULL,
                    ""ExternalPackageId"" text,
                    ""Barcode"" text,
                    ""CodBarcode"" text,
                    ""AwbPdfUrl"" text,
                    ""CurrentStatus"" text,
                    ""ArabicStatus"" text,
                    ""CodAmount"" double precision NOT NULL DEFAULT 0.0,
                    ""AssignedDriverName"" text,
                    ""AssignedDriverPhone"" text,
                    ""RawWebhookPayload"" text,
                    ""DispatchedAt"" timestamp with time zone NOT NULL DEFAULT (now()),
                    ""LastStatusUpdatedAt"" timestamp with time zone
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DeliveryProviderConfigs");

            migrationBuilder.DropTable(
                name: "DeliveryProviderLocationMappings");

            migrationBuilder.DropTable(
                name: "OrderShipmentMappings");

            migrationBuilder.DropColumn(
                name: "IsOversized",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "Latitude",
                table: "Addresses");

            migrationBuilder.DropColumn(
                name: "Longitude",
                table: "Addresses");
        }
    }
}
