using Blocko.Persistence;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace Bolcko.Web.App.Extensions;

/// <summary>
/// Extension methods for database initialization, migrations, and seeding
/// </summary>
public static class DatabaseExtensions
{
    #region Database Initialization

    /// <summary>
    /// Initializes the database with automatic migration and optional seeding
    /// </summary>
    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        await app.ApplyMigrationsAsync();
        await app.SeedDataAsync();
    }

    /// <summary>
    /// Applies pending database migrations automatically on startup
    /// </summary>
    private static async Task ApplyMigrationsAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<BlockoDbContext>();
        
        Log.Information("Applying database migrations...");
        await db.Database.MigrateAsync();
        
        // Apply additional schema changes that migrations might miss
        await ApplyRawSchemaChangesAsync(db);
        
        Log.Information("Database migrations applied successfully.");
    }

    /// <summary>
    /// Applies raw SQL schema changes for specific database features
    /// </summary>
    private static async Task ApplyRawSchemaChangesAsync(BlockoDbContext db)
    {
        try
        {
            // Add DeliveryToken column if it doesn't exist (PostgreSQL syntax)
            await db.Database.ExecuteSqlRawAsync(
                """ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "DeliveryToken" text;""");
            
            // Create DeliveryProviderLocationMappings table automatically if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "DeliveryProviderLocationMappings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProviderKey" text NOT NULL,
                    "SearchName" text NOT NULL,
                    "NormalizedSearchName" text NOT NULL,
                    "ExternalCityId" bigint NOT NULL,
                    "ExternalCityName" text,
                    "ExternalRegionId" bigint NOT NULL,
                    "ExternalRegionName" text,
                    "ExternalVillageId" bigint NOT NULL,
                    "ExternalVillageName" text,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now())
                );

                CREATE TABLE IF NOT EXISTS "VendorTeamMembers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "VendorId" integer NOT NULL,
                    "UserId" integer,
                    "FullName" text NOT NULL,
                    "Email" text NOT NULL,
                    "PhoneNumber" text NOT NULL DEFAULT '',
                    "JobTitle" text,
                    "RoleType" integer NOT NULL DEFAULT 2,
                    "CanManageCatalog" boolean NOT NULL DEFAULT true,
                    "CanManageOrders" boolean NOT NULL DEFAULT false,
                    "CanViewFinance" boolean NOT NULL DEFAULT false,
                    "CanManageTeam" boolean NOT NULL DEFAULT false,
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "InvitedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "JoinedAt" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS "ContractorProfiles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" integer NOT NULL,
                    "CompanyNameAr" text NOT NULL,
                    "CompanyNameEn" text,
                    "CommercialRegistrationNo" text,
                    "TaxNumber" text,
                    "ClassificationGrade" text NOT NULL DEFAULT 'الدرجة الأولى - إنشاء أبنية',
                    "JccaMembershipNumber" text,
                    "JccaCertificateDocUrl" text,
                    "CommercialRegistrationDocUrl" text,
                    "TaxCertificateDocUrl" text,
                    "IsJccaVerified" boolean NOT NULL DEFAULT false,
                    "Status" text NOT NULL DEFAULT 'Active',
                    "ContactPersonName" text,
                    "Phone" text,
                    "City" text NOT NULL DEFAULT 'عمان',
                    "RegisteredAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "VerifiedAt" timestamp with time zone
                );

                CREATE TABLE IF NOT EXISTS "VendorCustomCarriers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "VendorId" integer NOT NULL,
                    "CarrierName" text NOT NULL,
                    "ContactPhone" text NOT NULL,
                    "ContactPerson" text,
                    "FleetType" text NOT NULL DEFAULT 'تريلات مسطحة وونشات ثقيلة',
                    "BaseTariffJod" numeric NOT NULL DEFAULT 25.00,
                    "CraneFeeJod" numeric NOT NULL DEFAULT 35.00,
                    "CoveredGovernorates" text NOT NULL DEFAULT 'عمان, الزرقاء, البلقاء',
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now())
                );

                -- Catalog Moderation (GOV-01) & Wholesale Tier Pricing (B2B-01)
                ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "ModerationStatus" text NOT NULL DEFAULT 'Approved';
                ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "RejectionReason" text;
                ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "ModeratedAt" timestamp with time zone;

                CREATE TABLE IF NOT EXISTS "ProductTierPricings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProductId" integer NOT NULL,
                    "MinQuantity" integer NOT NULL,
                    "MaxQuantity" integer,
                    "UnitPrice" numeric NOT NULL DEFAULT 0.00,
                    "DiscountPercentage" numeric NOT NULL DEFAULT 0.00,
                    "TierName" text,
                    CONSTRAINT "FK_ProductTierPricings_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS "IX_ProductTierPricings_ProductId" ON "ProductTierPricings" ("ProductId");

                -- Heavy Hauler & 3PL Carrier KYC Columns (LOG-01)
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "NationalId" text;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "HeavyLicenseCategory" text;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "LicenseDocUrl" text;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "RegistrationDocUrl" text;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "VehiclePhotoUrl" text;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "CliqAlias" text;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "CapacityTons" integer NOT NULL DEFAULT 15;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "CoveredGovernorate" text;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "ApprovedAt" timestamp with time zone;
                ALTER TABLE "DeliveryDrivers" ADD COLUMN IF NOT EXISTS "RejectionReason" text;

                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "TaxId" text;
                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "TransportCommissionLicense" text;
                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "CommercialRegisterDocUrl" text;
                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "TransportLicenseDocUrl" text;
                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "CliqAlias" text;
                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "TotalTrucksCount" integer NOT NULL DEFAULT 5;
                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "IsApproved" boolean NOT NULL DEFAULT false;
                ALTER TABLE "DeliveryCompanies" ADD COLUMN IF NOT EXISTS "RejectionReason" text;

                -- LOG-03 Heavy Transport Load Radar, Weighbridge & e-POD Columns
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "MaterialType" text;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "WeightTons" numeric;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "WeighbridgeTicketUrl" text;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "GrossWeightTons" numeric;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "TareWeightTons" numeric;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "WeighedAt" timestamp with time zone;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "DeliveryOtpCode" text;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "IsPodVerified" boolean NOT NULL DEFAULT false;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "PodVerifiedAt" timestamp with time zone;

                -- LOG-05 Vendor Logistics Sovereignty & Capacity Overflow Columns
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "PlatformFreightFee" numeric NOT NULL DEFAULT 0.00;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "FulfillmentType" text NOT NULL DEFAULT 'OwnFleet';
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "WaybillNumber" text;
                ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "IsCapacityOverflow" boolean NOT NULL DEFAULT false;

                ALTER TABLE "VendorProfiles" ADD COLUMN IF NOT EXISTS "FulfillmentMode" text NOT NULL DEFAULT 'OwnFleet';

                -- LOG-06 Instant CliQ Carrier Wallet Payout & Escrow Release Table
                CREATE TABLE IF NOT EXISTS "CarrierPayoutTransactions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "DeliveryJobId" integer,
                    "DriverId" integer,
                    "DeliveryCompanyId" integer,
                    "OrderId" integer NOT NULL,
                    "GrossFreightAmountJod" numeric NOT NULL DEFAULT 0.00,
                    "PlatformTakeRateFee" numeric NOT NULL DEFAULT 0.00,
                    "PayoutAmountJod" numeric NOT NULL DEFAULT 0.00,
                    "PayoutMethod" text NOT NULL DEFAULT 'CliQ',
                    "DestinationCliqAlias" text,
                    "DestinationBankIban" text,
                    "TransactionReference" text NOT NULL,
                    "Status" text NOT NULL DEFAULT 'Completed',
                    "InitiatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "SettledAt" timestamp with time zone,
                    "DeliveryOtpVerified" text,
                    "EpodDocumentUrl" text,
                    "IsEscrowReleased" boolean NOT NULL DEFAULT false,
                    "DisputeReason" text,
                    "DisputePhotoEvidenceUrl" text,
                    "DisputedAt" timestamp with time zone
                );
                """);

            // Ensure DeliveryProviderConfigs has origin and sender columns
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "DeliveryProviderConfigs" ADD COLUMN IF NOT EXISTS "PickupAddressLine" text NOT NULL DEFAULT 'عمان - رأس العين - مستودع القناص';
                ALTER TABLE "DeliveryProviderConfigs" ADD COLUMN IF NOT EXISTS "PickupCityId" bigint NOT NULL DEFAULT 1130;
                ALTER TABLE "DeliveryProviderConfigs" ADD COLUMN IF NOT EXISTS "PickupRegionId" bigint NOT NULL DEFAULT 33;
                ALTER TABLE "DeliveryProviderConfigs" ADD COLUMN IF NOT EXISTS "PickupVillageId" bigint NOT NULL DEFAULT 6176;
                ALTER TABLE "DeliveryProviderConfigs" ADD COLUMN IF NOT EXISTS "SenderStoreName" text NOT NULL DEFAULT 'متجر بلوكو لتوريدات البناء';
                ALTER TABLE "DeliveryProviderConfigs" ADD COLUMN IF NOT EXISTS "SenderPhone" text NOT NULL DEFAULT '0782023800';
                ALTER TABLE "DeliveryProviderConfigs" ADD COLUMN IF NOT EXISTS "DefaultDeliveryFee" numeric NOT NULL DEFAULT 3.00;
                """);

            // Seed / Update GLC default config to Ras Al-Ain (Bolcko Warehouse)
            await db.Database.ExecuteSqlRawAsync(
                """
                UPDATE "DeliveryProviderConfigs" 
                SET "PickupAddressLine" = 'عمان - رأس العين - مستودع بلوكو (مجمع القناص)',
                    "PickupCityId" = 1130,
                    "PickupRegionId" = 33,
                    "PickupVillageId" = 6176,
                    "SenderStoreName" = 'متجر بلوكو لتوريدات البناء',
                    "SenderPhone" = '0782023800',
                    "DefaultDeliveryFee" = 2.50
                WHERE "ProviderKey" = 'glc' OR "ProviderKey" = 'LogesTechs';

                -- Ensure Base AppSettings exist for Delivery
                INSERT INTO "AppSettings" ("Key", "Value", "Description", "LastUpdated")
                SELECT 'BaseCourierCost', '1.75', 'تكلفة شركة الشحن الموحدة لكافة المحافظات (دينار)', now()
                WHERE NOT EXISTS (SELECT 1 FROM "AppSettings" WHERE "Key" = 'BaseCourierCost');

                INSERT INTO "AppSettings" ("Key", "Value", "Description", "LastUpdated")
                SELECT 'ShippingFee', '2.50', 'رسوم التوصيل الافتراضية للزبون (دينار)', now()
                WHERE NOT EXISTS (SELECT 1 FROM "AppSettings" WHERE "Key" = 'ShippingFee');

                INSERT INTO "AppSettings" ("Key", "Value", "Description", "LastUpdated")
                SELECT 'EnableExpressDelivery', 'true', 'تفعيل خيار التوصيل الفوري السريع', now()
                WHERE NOT EXISTS (SELECT 1 FROM "AppSettings" WHERE "Key" = 'EnableExpressDelivery');

                INSERT INTO "AppSettings" ("Key", "Value", "Description", "LastUpdated")
                SELECT 'ExpressDeliveryFee', '5.00', 'رسوم التوصيل الفوري', now()
                WHERE NOT EXISTS (SELECT 1 FROM "AppSettings" WHERE "Key" = 'ExpressDeliveryFee');

                -- Seed all 12 Jordanian Governorates in ShippingRates table
                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'عمان', 'Amman', 2.50 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'عمان');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'الزرقاء', 'Zarqa', 3.00 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'الزرقاء');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'البلقاء', 'Balqa', 3.00 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'البلقاء');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'مادبا', 'Madaba', 3.00 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'مادبا');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'إربد', 'Irbid', 3.50 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'إربد');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'جرش', 'Jerash', 3.50 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'جرش');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'عجلون', 'Ajloun', 3.50 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'عجلون');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'المفرق', 'Mafraq', 3.50 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'المفرق');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'الكرك', 'Karak', 4.00 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'الكرك');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'الطفيلة', 'Tafilah', 4.00 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'الطفيلة');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'معان', 'Ma''an', 4.00 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'معان');

                INSERT INTO "ShippingRates" ("CityName", "CityNameEn", "Rate")
                SELECT 'العقبة', 'Aqaba', 4.00 WHERE NOT EXISTS (SELECT 1 FROM "ShippingRates" WHERE "CityName" = 'العقبة');
                """);

            // Seed verified Jordanian Governorates and Cities into DeliveryProviderLocationMappings for GLC/LogesTechs
            await db.Database.ExecuteSqlRawAsync(
                """
                -- Amman / رأس العين
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'راس العين', 'راس العين', 1130, 'حي نزال', 33, 'Amman', 6176, 'راس العين', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 6176);

                -- Amman Main
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'عمان', 'عمان', 395, 'Amman', 33, 'Amman', 17798, 'عمان', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 17798);

                -- Zarqa Main
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'الزرقاء', 'الزرقاء', 11804, 'الزرقاء', 44, 'Zarqa''', 40208, 'الزرقاء', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 40208);

                -- Irbid Main
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'اربد', 'اربد', 1184, 'اربد', 43, 'Irbid', 1089895, 'اربد', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 1089895);

                -- Aqaba Main
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'العقبة', 'العقبة', 388, 'Aqaba', 40, 'Al Aqaba', 1089576, 'العقبة', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 1089576);

                -- Balqa / As-Salt
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'السلط', 'السلط', 1180, 'السلط', 242, 'السلط', 6421, 'السلط', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 6421);

                -- Madaba
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'مادبا', 'مادبا', 1181, 'مادبا', 34, 'Madaba', 6432, 'مادبا', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 6432);

                -- Jerash
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'جرش', 'جرش', 1177, 'جرش', 41, 'Jarash', 6383, 'جرش', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 6383);

                -- Ajloun
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'عجلون', 'عجلون', 1178, 'عجلون', 42, 'Ajloun', 6382, 'عجلون', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 6382);

                -- Al Karak
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'الكرك', 'الكرك', 393, 'Karak', 37, 'Al Karak', 2597, 'الكرك', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 2597);

                -- Maan
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'معان', 'معان', 1174, 'معان', 38, 'Maan', 6327, 'معان', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 6327);

                -- Al Mafraq
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'المفرق', 'المفرق', 1179, 'المفرق', 36, 'Al Mafraq', 6391, 'المفرق', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 6391);

                -- Tafilah
                INSERT INTO "DeliveryProviderLocationMappings" ("ProviderKey", "SearchName", "NormalizedSearchName", "ExternalCityId", "ExternalCityName", "ExternalRegionId", "ExternalRegionName", "ExternalVillageId", "ExternalVillageName", "CreatedAt")
                SELECT 'glc', 'الطفيلة', 'الطفيلة', 817450, 'الطفيلة', 39, 'Al Tfaile', 1089496, 'الطفيلة', now()
                WHERE NOT EXISTS (SELECT 1 FROM "DeliveryProviderLocationMappings" WHERE "ProviderKey" = 'glc' AND "ExternalVillageId" = 1089496);
                """);

            // Create OrderShipmentMappings table automatically if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "OrderShipmentMappings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "OrderId" integer NOT NULL,
                    "ProviderKey" text NOT NULL,
                    "ExternalPackageId" text,
                    "Barcode" text,
                    "CodBarcode" text,
                    "AwbPdfUrl" text,
                    "CurrentStatus" text,
                    "ArabicStatus" text,
                    "CodAmount" double precision NOT NULL DEFAULT 0.0,
                    "AssignedDriverName" text,
                    "AssignedDriverPhone" text,
                    "RawWebhookPayload" text,
                    "DispatchedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "LastStatusUpdatedAt" timestamp with time zone
                );
                """);

            // Create MarketPrices table if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "MarketPrices" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "MaterialName" text NOT NULL,
                    "Price" numeric NOT NULL,
                    "UnitOfMeasure" text NOT NULL,
                    "Currency" text NOT NULL DEFAULT 'JOD',
                    "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now()),
                    "Source" text,
                    "MaterialNameEn" text,
                    "MaterialCategory" text NOT NULL DEFAULT 'General',
                    "PreviousPrice" numeric,
                    "GlobalPriceUsd" numeric,
                    "ChangePercent" double precision NOT NULL DEFAULT 0,
                    "Trend" text NOT NULL DEFAULT 'stable',
                    "Specification" text,
                    "IsLiveAutoUpdated" boolean NOT NULL DEFAULT false,
                    "CityRatesJson" text
                );
                """);

            // Ensure all MarketPrices columns exist (for pre-existing tables on Production Linux)
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "MaterialName" text NOT NULL DEFAULT '';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Price" numeric NOT NULL DEFAULT 0;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "UnitOfMeasure" text NOT NULL DEFAULT '';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Currency" text NOT NULL DEFAULT 'JOD';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now());
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Source" text;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "MaterialNameEn" text;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "MaterialCategory" text NOT NULL DEFAULT 'General';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "PreviousPrice" numeric;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "GlobalPriceUsd" numeric;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "ChangePercent" double precision NOT NULL DEFAULT 0;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Trend" text NOT NULL DEFAULT 'stable';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Specification" text;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "IsLiveAutoUpdated" boolean NOT NULL DEFAULT true;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "CityRatesJson" text;
                """);

            // Create FAQItems table if it doesn't exist in Postgres (e.g. Linux Production server)
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "FAQItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "QuestionAr" text NOT NULL,
                    "AnswerAr" text NOT NULL,
                    "QuestionEn" text,
                    "AnswerEn" text,
                    "PageTarget" text NOT NULL DEFAULT 'calculator',
                    "DisplayOrder" integer NOT NULL DEFAULT 0,
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "UpdatedAt" timestamp with time zone
                );
                """);

            // Ensure all FAQItems columns exist
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "QuestionAr" text NOT NULL DEFAULT '';
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "AnswerAr" text NOT NULL DEFAULT '';
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "QuestionEn" text;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "AnswerEn" text;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "PageTarget" text NOT NULL DEFAULT 'calculator';
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "DisplayOrder" integer NOT NULL DEFAULT 0;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT true;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone;
                """);

            // Create SEOMetadata table if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "SEOMetadata" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "PageName" text NOT NULL,
                    "PageTitle" text,
                    "MetaDescription" text,
                    "MetaKeywords" text,
                    "PageUrl" text,
                    "PageOrder" integer,
                    "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now())
                );
                """);

            // Create SupplierProviderConfigs table if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "SupplierProviderConfigs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SupplierName" text NOT NULL,
                    "SupplierKey" text NOT NULL,
                    "BaseUrl" text NOT NULL,
                    "ApiPhoneNumber" text,
                    "ApiPassword" text,
                    "ApiEmail" text,
                    "AuthToken" text,
                    "ExternalCustomerId" integer,
                    "ExternalUserId" integer,
                    "PickupAddressLine" text,
                    "PickupCityId" bigint NOT NULL DEFAULT 395,
                    "PickupRegionId" bigint NOT NULL DEFAULT 33,
                    "PickupVillageId" bigint NOT NULL DEFAULT 18076,
                    "ContactPersonName" text,
                    "ContactPhoneNumber" text,
                    "AutoDispatchEnabled" boolean NOT NULL DEFAULT true,
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "CustomHeadersJson" text,
                    "CustomPayloadMappingJson" text,
                    "Notes" text,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now())
                );
                """);

            // Ensure Order and Product supplier sourcing columns exist
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "PrimarySupplierKey" text DEFAULT 'qannas';
                ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "ExternalSupplierOrderNumber" text;
                ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "SourcingStatus" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "SourcingNotes" text;

                ALTER TABLE "OrderItems" ADD COLUMN IF NOT EXISTS "SupplierKey" text;
                ALTER TABLE "OrderItems" ADD COLUMN IF NOT EXISTS "ExternalSupplierVariantId" integer;
                ALTER TABLE "OrderItems" ADD COLUMN IF NOT EXISTS "ExternalSupplierOrderId" text;
                ALTER TABLE "OrderItems" ADD COLUMN IF NOT EXISTS "SourcingStatus" integer NOT NULL DEFAULT 0;
                ALTER TABLE "OrderItems" ADD COLUMN IF NOT EXISTS "SourcingNotes" text;

                ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "SupplierKey" text DEFAULT 'qannas';
                ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "ExternalSupplierVariantId" integer;
                """);

            // Seed Qannas Supplier default record if not exists
            await db.Database.ExecuteSqlRawAsync(
                """
                INSERT INTO "SupplierProviderConfigs" 
                ("SupplierName", "SupplierKey", "BaseUrl", "ApiPhoneNumber", "ApiPassword", "ApiEmail", "PickupAddressLine", "PickupCityId", "PickupRegionId", "PickupVillageId", "ContactPersonName", "ContactPhoneNumber", "AutoDispatchEnabled", "IsActive", "CreatedAt", "UpdatedAt")
                SELECT 'شركة القناص لتجارة الجملة', 'qannas', 'https://api.qannasjo.com/', '0782023800', 'Qannas@100', 'qannasco@gmail.com', 'عمان - رأس العين - مستودع القناص', 395, 33, 18076, 'موظف بلوكو - مستودع رأس العين', '0782023800', true, true, now(), now()
                WHERE NOT EXISTS (SELECT 1 FROM "SupplierProviderConfigs" WHERE "SupplierKey" = 'qannas');
                """);

            // Ensure all SEOMetadata columns exist
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageName" text NOT NULL DEFAULT '';
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageTitle" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "MetaDescription" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "MetaKeywords" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageUrl" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageOrder" integer;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now());
                """);

            // Seed default MarketPrices if table is empty
            await db.Database.ExecuteSqlRawAsync(
                """
                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'حديد تسليح مشوه (Grade 60) - حديد الأردن والوطنية', 515.00, 'طن', 'JOD', now(), 'مصانع الصلب الأردنية المعتمدة', 'Jordan & National Steel Rebar (Grade 60)', 'Steel', 518.00, 725.00, -0.58, 'down', 'عالي المقاومة ومطابق للمواصفة القياسية الأردنية JS 29:2018 وكود نقابة المهندسين.', true
                WHERE NOT EXISTS (SELECT 1 FROM "MarketPrices" LIMIT 1);

                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'إسمنت بورتلاندي بوزولاني وبورتلاندي عادي (لافارج والقطرانة)', 88.00, 'طن', 'JOD', now(), 'شركات الإسمنت الأردنية الرسمية', 'Lafarge & Qatrana Portland Cement CEM I', 'Cement', 88.00, 124.00, 0.0, 'stable', 'أكياس 50 كغم ومطابق للمواصفة الأردنية JS 30-1 لقوة التحمل والمتانة الإنشائية.', true
                WHERE (SELECT COUNT(*) FROM "MarketPrices") = 1;

                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'خرسانة جاهزة B250 / B300 (المناصير ولافارج للبيتون)', 43.50, 'متر مكعب', 'JOD', now(), 'محطات ومصانع الخرسانة الجاهزة الكبرى', 'Ready-Mix Concrete B250/B300 (Manaseer / Lafarge)', 'Concrete', 43.50, 61.35, 0.0, 'stable', 'شاملة المضخة والفحص المخبري لمقاومة الكسر بعد 28 يوماً.', true
                WHERE (SELECT COUNT(*) FROM "MarketPrices") = 2;

                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'طوب إسمنتي آلي مفرغ وهوردي (10 / 15 / 20 سم)', 0.36, 'حبة', 'JOD', now(), 'مصانع الطوب الآلية المعتمدة', 'Automated Hollow & Rib Concrete Blocks', 'Blocks', 0.36, 0.51, 0.0, 'stable', 'معالج بالبخار ومطابق للأبعاد الهندسية وعزل الصوت والحرارة.', true
                WHERE (SELECT COUNT(*) FROM "MarketPrices") = 3;
                """);

            // Seed default FAQs if table is empty
            await db.Database.ExecuteSqlRawAsync(
                """
                INSERT INTO "FAQItems" ("QuestionAr", "AnswerAr", "QuestionEn", "AnswerEn", "PageTarget", "DisplayOrder", "IsActive", "CreatedAt")
                SELECT 
                    'كيف يتم احتساب كمية حديد التسليح للمشروع؟',
                    'يتم احتساب كمية الحديد بناءً على الكودات الهندسية الأردنية المعتمدة للمباني السكنية والتجارية بمعدل يتراوح بين 38 إلى 45 كغم لكل متر مربع مسطح من إجمالي مساحة البناء (Built-up Area)، وتزداد النسبة تلقائياً في حال اختيار أساسات اللبشة (Raft) أو الاستخدام التجاري.',
                    'calculator', 1, true, now()
                WHERE NOT EXISTS (SELECT 1 FROM "FAQItems" LIMIT 1);
                """);

            // Seed default SEO Metadata for Calculator and Core landing pages if not exists
            await db.Database.ExecuteSqlRawAsync(
                """
                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'Home',
                    'بلوكو لتوريد مواد البناء | BLOCKO Construction Supplies',
                    'منصة توريدات مواد البناء الأولى والمثالية في الأردن. أسعار يومية لحديد التسليح، الإسمنت، والخرسانة مباشرة من المصنع إلى موقعك.',
                    'مواد بناء، حديد تسليح الأردن، إسمنت، خرسانة جاهزة، توريد مشاريع، بلوكو، BLOCKO',
                    '/',
                    1,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'Home');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator',
                    'حاسبة تكلفة البناء وكميات المواد في الأردن 2026 | بلوكو',
                    'احسب كميات وتكاليف حديد التسليح، الإسمنت، الخرسانة الجاهزة، والطوب الإسمنتي لمشروعك في الأردن بدقة هندسية وفق كودات البناء وأسعار السوق اللحظية.',
                    'حاسبة تكلفة البناء الأردن, حساب كميات الحديد, اسعار الاسمنت في الاردن, اسعار الحديد اليوم عمان, تكلفة بناء بيت عظم, اسعار الخرسانة الجاهزة, بلوكو',
                    '/calculator',
                    2,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-stone',
                    'حاسبة تكلفة وأسعار حجر البناء والواجهات الأردنية 2026 | بلوكو',
                    'احسب مساحات وتكاليف حجر الرويشد ومعان والصناعي والكرانيش والبراويز لمشروعك في الأردن بدقة هندسية وخصم فتحات وهالك معتمد.',
                    'حاسبة حجر البناء الاردن, اسعار حجر الرويشد, حجر معان نخب اول, تكلفة واجهات حجر عمارة, كرانيش حجر صناعي, بلوكو',
                    '/calculator?category=stone',
                    3,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-stone');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-steel',
                    'حاسبة كميات وأوزان حديد التسليح للمباني في الأردن 2026 | بلوكو',
                    'احسب أطنان حديد التسليح (Grade 60) بدقة حسب عدد الطوابق ونظام العقدة وتسليح الأعمدة ومخططات البناء الأردنية.',
                    'حاسبة حديد البناء الاردن, كمية الحديد لطابقين, اسعار حديد التسليح اليوم عمان, حاسبة حديد القواعد والاعمدة, بلوكو',
                    '/calculator?category=steel',
                    4,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-steel');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-concrete',
                    'حاسبة كميات الباطون والخرسانة الجاهزة في الأردن 2026 | بلوكو',
                    'احسب أمتار الخرسانة الجاهزة B250 و B300 مع المضخة للعقدات والقواعد والشناجات بأسعار الخلاطات اللحظية واصلة الموقع.',
                    'حاسبة كميات الباطون, اسعار الخرسانة الجاهزة الاردن, متر باطون صبة العقدة, خلاطات الخرسانة عمان, بلوكو',
                    '/calculator?category=concrete',
                    5,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-concrete');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-finishes',
                    'حاسبة تكاليف التشطيب والدهان والعوازل في الأردن 2026 | بلوكو',
                    'تقدير فوري لتكاليف الدهانات، العوازل المائية والحرارية، التأسيسات الكهروميكانيكية والقصارة لمشروعك السكني في الأردن.',
                    'تكلفة تشطيب شقة الاردن, اسعار دهانات جوتن وسكيب عمان, رولات عزل اسطح, تكلفة المتر تشطيب ديلوكس, بلوكو',
                    '/calculator?category=finishes',
                    6,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-finishes');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-blocks',
                    'حاسبة كميات وأسعار الطوب الإسمنتي والهوردي والربس في الأردن | بلوكو',
                    'احسب عدد حبات الطوب الإسمنتي 10 و 15 و 20 سم وطوب الهوردي والربس للعقدات والجدران الخارجية والقواطع مع نسبة الكسر والهالك.',
                    'حاسبة طوب البناء الاردن, كمية الطوب لعمارة, سعر طوب 20 في الاردن, طوب هوردي عصب, اسعار الطوب الاسمنتي عمان, بلوكو',
                    '/calculator?category=blocks',
                    7,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-blocks');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-cement',
                    'حاسبة كميات الإسمنت والشيد والرمل ومونة البناء في الأردن | بلوكو',
                    'احسب عدد أكياس الإسمنت وأمتار الرمل والشيد اللازمة للمونة والبناء والقصارة وصبيات النظافة بمشروعك الإنشائي وفق كودات البناء.',
                    'حاسبة اكياس الاسمنت, كم كيس اسمنت للبناء, اسعار الاسمنت في الاردن اليوم, رمل صويلح وشيد, مونة القصارة, بلوكو',
                    '/calculator?category=cement',
                    8,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-cement');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-skeleton',
                    'حاسبة تكلفة بناء عظم المتر المربع في الأردن 2026 | بلوكو',
                    'تقدير دقيق لتكلفة بناء المتر المربع عظم بالمواد والعمالة في الأردن. تشمل الحفر، الخرسانة، الحديد، العزل، والطوب مع جدول كميات تفصيلي.',
                    'تكلفة المتر عظم الاردن 2026, تكلفة بناء طابق عظم, حساب تكاليف البناء عظم, اسعار المقاولات عظم عمان, بلوكو',
                    '/calculator?category=skeleton',
                    9,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-skeleton');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-villa',
                    'حاسبة تكلفة بناء فيلا سكنية كاملة في الأردن (عظم وتشطيب) | بلوكو',
                    'احسب التكلفة التقديرية لبناء فيلا سكنية طابق أو طابقين مع روف وتسوية في عمان والمحافظات بأسعار المواد والتشطيبات اللحظية.',
                    'تكلفة بناء فيلا في الاردن, كم يكلف بناء فيلا 300 متر, تكلفة تشطيب فيلا عمان, حاسبة بناء الفلل, بلوكو',
                    '/calculator?type=villa',
                    10,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-villa');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-building',
                    'حاسبة تكلفة بناء عمارة سكنية استثمارية في الأردن (طوابق متعددة) | بلوكو',
                    'احسب تكلفة بناء عمارات سكنية وتجارية من طابقين حتى 6 طوابق في الأردن. جدول كميات شامل للحديد والخرسانة والحجر والمصاعد والعمالة.',
                    'تكلفة بناء عمارة 4 طوابق الاردن, تكلفة عمارة سكنية استثمارية, دراسة جدوى بناء عمارة عمان, حاسبة كميات العمارات, بلوكو',
                    '/calculator?type=building',
                    11,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-building');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-slabs',
                    'حاسبة أسقف البناء (عقدة عصب، فلات سلاب، بلاطة مصمتة) | بلوكو',
                    'مقارنة هندسية وتقدير كميات حديد التسليح والخرسانة وطوب الربس لأنظمة الأسقف المختلفة في كود البناء الأردني.',
                    'حاسبة عقدة عصب, تكلفة فلات سلاب الاردن, مقارنة انواع الاسقف الخرسانية, كمية الحديد في عقدة العصب, بلوكو',
                    '/calculator?category=slabs',
                    12,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-slabs');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-columns',
                    'حاسبة تسليح الأعمدة الإنشائية وقضبان الحديد وكود الزلازل الأردني | بلوكو',
                    'حساب كميات حديد الأعمدة 6 و 8 و 10 قضبان مع الكانات والخرسانة الإنشائية ومراعاة أحمال الرياح والزلازل في الأردن.',
                    'تسليح الاعمدة كمية الحديد, اعمدة 8 قضبان, كود الزلازل الاردني تسليح, حساب كانات الاعمدة, بلوكو',
                    '/calculator?category=columns',
                    13,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-columns');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'calculator-prices',
                    'أسعار مواد البناء اليوم في الأردن (حديد، باطون، إسمنت، طوب) 2026 | بلوكو',
                    'شريط أسعار مواد البناء الإنشائية اليوم في الأردن. أسعار طن الحديد والخرسانة الجاهزة وأكياس الإسمنت مع التوصيل لموقع المشروع.',
                    'اسعار مواد البناء اليوم الاردن, اسعار الحديد اليوم عمان, سعر طن الاسمنت الاردن, سعر متر الباطون الجاهز, بلوكو',
                    '/calculator?tab=prices',
                    14,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'calculator-prices');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'Categories',
                    'مجموعات التوريد والأقسام الرئيسية | BLOCKO Categories',
                    'استكشف مجموعات توريد مواد البناء والأقسام الرئيسية للعدد، الأدوات، الأدوات الصحية، والمواد اللاصقة.',
                    'أقسام مواد البناء، مستلزمات سباكة، مواد لاصقة، لوازم إنشائية',
                    '/Shop/Category',
                    15,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'Categories');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'About',
                    'من نحن | بلوكو لتوريد مواد البناء والحلول الإنشائية',
                    'تعرف على منصة بلوكو، الرائدة في توريد مواد البناء والمستلزمات الإنشائية في المملكة الأردنية الهاشمية بأعلى معايير الجودة والسرعة.',
                    'عن بلوكو, شركة مواد بناء الاردن, توريد مشاريع عمان, من نحن بلوكو',
                    '/Shop/Home/AboutUs',
                    16,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'About');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'Quote',
                    'طلب تسعيرة وتوريد مشاريع رسمي | استدراج عروض أسعار بلوكو',
                    'اطلب عرض سعر رسمي لمشروعك الإنشائي لتوريد كميات الحديد، الإسمنت، الخرسانة، ومواد التشطيب بأسعار الجملة المعتمدة.',
                    'طلب تسعيرة مواد بناء, استدراج عروض اسعار, تسعير مشاريع عظم, عروض اسعار حديد واسمنت',
                    '/Shop/Quote/Request',
                    17,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'Quote');

                INSERT INTO "SEOMetadata" ("PageName", "PageTitle", "MetaDescription", "MetaKeywords", "PageUrl", "PageOrder", "LastUpdated")
                SELECT 
                    'Contact',
                    'اتصل بنا لطلب عروض الأسعار وتوريد المشاريع | Contact BLOCKO',
                    'تواصل مع مستشاري توريد مواد البناء في الأردن. نحن متواجدون لمساعدتك في تسعير مشاريعك الإنشائية وتوريدها.',
                    'اتصال بلوكو، خدمة العملاء، تسعير مواد البناء، توريد خرسانة الأردن',
                    '/Shop/Home/Contact',
                    18,
                    now()
                WHERE NOT EXISTS (SELECT 1 FROM "SEOMetadata" WHERE "PageName" = 'Contact');
                """);

            Log.Information("Database tables (Delivery, FAQItems, MarketPrices, SEOMetadata) verified/created successfully via raw SQL.");
        }
        catch (Exception sqlEx)
        {
            Log.Warning(sqlEx, "Failed to apply raw SQL schema changes.");
        }
    }

    #endregion

    #region Data Seeding

    /// <summary>
    /// Seeds initial data based on environment
    /// </summary>
    private static async Task SeedDataAsync(this WebApplication app)
    {
        // Only seed identity data in Development
        if (app.Environment.IsDevelopment())
        {
            await app.SeedIdentityDataAsync();
            Log.Information("Development identity data seeded");
        }
        else
        {
            // In Production, the /Setup page handles first-run admin creation
            Log.Information("Production mode: skipping automatic data seeding. Use /Setup for initial admin creation.");
        }
    }

    #endregion
}
