using Blocko.Persistence;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace Bolcko.Web.App.Extensions;

/// <summary>
/// Extension methods for database initialization, migrations, and seeding
/// </summary>
public static class DatabaseExtensions
{
    #region Database Initialization

    /// <summary>
    /// Initializes the database with automatic migration and optional seeding
    /// </summary>
    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        await app.ApplyMigrationsAsync();
        await app.SeedDataAsync();
    }

    /// <summary>
    /// Applies pending database migrations automatically on startup
    /// </summary>
    private static async Task ApplyMigrationsAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<BlockoDbContext>();
        
        Log.Information("Applying database migrations...");
        await db.Database.MigrateAsync();
        
        // Apply additional schema changes that migrations might miss
        await ApplyRawSchemaChangesAsync(db);
        
        Log.Information("Database migrations applied successfully.");
    }

    /// <summary>
    /// Applies raw SQL schema changes for specific database features
    /// </summary>
    private static async Task ApplyRawSchemaChangesAsync(BlockoDbContext db)
    {
        try
        {
            // Add DeliveryToken column if it doesn't exist (PostgreSQL syntax)
            await db.Database.ExecuteSqlRawAsync(
                """ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "DeliveryToken" text;""");
            
            // Create DeliveryProviderLocationMappings table automatically if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "DeliveryProviderLocationMappings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProviderKey" text NOT NULL,
                    "SearchName" text NOT NULL,
                    "NormalizedSearchName" text NOT NULL,
                    "ExternalCityId" bigint NOT NULL,
                    "ExternalCityName" text,
                    "ExternalRegionId" bigint NOT NULL,
                    "ExternalRegionName" text,
                    "ExternalVillageId" bigint NOT NULL,
                    "ExternalVillageName" text,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now())
                );
                """);

            Log.Information("DeliveryProviderLocationMappings table verified/created successfully via raw SQL.");
        }
        catch (Exception sqlEx)
        {
            Log.Warning(sqlEx, "Failed to apply raw SQL schema changes.");
        }
    }

    #endregion

    #region Data Seeding

    /// <summary>
    /// Seeds initial data based on environment
    /// </summary>
    private static async Task SeedDataAsync(this WebApplication app)
    {
        // Only seed identity data in Development
        if (app.Environment.IsDevelopment())
        {
            await app.SeedIdentityDataAsync();
            Log.Information("Development identity data seeded");
        }
        else
        {
            // In Production, the /Setup page handles first-run admin creation
            Log.Information("Production mode: skipping automatic data seeding. Use /Setup for initial admin creation.");
        }
    }

    #endregion
}
