using Blocko.Persistence;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace Bolcko.Web.App.Extensions;

/// <summary>
/// Extension methods for database initialization, migrations, and seeding
/// </summary>
public static class DatabaseExtensions
{
    #region Database Initialization

    /// <summary>
    /// Initializes the database with automatic migration and optional seeding
    /// </summary>
    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        await app.ApplyMigrationsAsync();
        await app.SeedDataAsync();
    }

    /// <summary>
    /// Applies pending database migrations automatically on startup
    /// </summary>
    private static async Task ApplyMigrationsAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<BlockoDbContext>();
        
        Log.Information("Applying database migrations...");
        await db.Database.MigrateAsync();
        
        // Apply additional schema changes that migrations might miss
        await ApplyRawSchemaChangesAsync(db);
        
        Log.Information("Database migrations applied successfully.");
    }

    /// <summary>
    /// Applies raw SQL schema changes for specific database features
    /// </summary>
    private static async Task ApplyRawSchemaChangesAsync(BlockoDbContext db)
    {
        try
        {
            // Add DeliveryToken column if it doesn't exist (PostgreSQL syntax)
            await db.Database.ExecuteSqlRawAsync(
                """ALTER TABLE "DeliveryJobs" ADD COLUMN IF NOT EXISTS "DeliveryToken" text;""");
            
            // Create DeliveryProviderLocationMappings table automatically if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "DeliveryProviderLocationMappings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProviderKey" text NOT NULL,
                    "SearchName" text NOT NULL,
                    "NormalizedSearchName" text NOT NULL,
                    "ExternalCityId" bigint NOT NULL,
                    "ExternalCityName" text,
                    "ExternalRegionId" bigint NOT NULL,
                    "ExternalRegionName" text,
                    "ExternalVillageId" bigint NOT NULL,
                    "ExternalVillageName" text,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now())
                );
                """);

            // Create OrderShipmentMappings table automatically if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "OrderShipmentMappings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "OrderId" integer NOT NULL,
                    "ProviderKey" text NOT NULL,
                    "ExternalPackageId" text,
                    "Barcode" text,
                    "CodBarcode" text,
                    "AwbPdfUrl" text,
                    "CurrentStatus" text,
                    "ArabicStatus" text,
                    "CodAmount" double precision NOT NULL DEFAULT 0.0,
                    "AssignedDriverName" text,
                    "AssignedDriverPhone" text,
                    "RawWebhookPayload" text,
                    "DispatchedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "LastStatusUpdatedAt" timestamp with time zone
                );
                """);

            // Create MarketPrices table if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "MarketPrices" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "MaterialName" text NOT NULL,
                    "Price" numeric NOT NULL,
                    "UnitOfMeasure" text NOT NULL,
                    "Currency" text NOT NULL DEFAULT 'JOD',
                    "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now()),
                    "Source" text,
                    "MaterialNameEn" text,
                    "MaterialCategory" text NOT NULL DEFAULT 'General',
                    "PreviousPrice" numeric,
                    "GlobalPriceUsd" numeric,
                    "ChangePercent" double precision NOT NULL DEFAULT 0,
                    "Trend" text NOT NULL DEFAULT 'stable',
                    "Specification" text,
                    "IsLiveAutoUpdated" boolean NOT NULL DEFAULT false,
                    "CityRatesJson" text
                );
                """);

            // Ensure all MarketPrices columns exist (for pre-existing tables on Production Linux)
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "MaterialName" text NOT NULL DEFAULT '';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Price" numeric NOT NULL DEFAULT 0;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "UnitOfMeasure" text NOT NULL DEFAULT '';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Currency" text NOT NULL DEFAULT 'JOD';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now());
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Source" text;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "MaterialNameEn" text;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "MaterialCategory" text NOT NULL DEFAULT 'General';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "PreviousPrice" numeric;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "GlobalPriceUsd" numeric;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "ChangePercent" double precision NOT NULL DEFAULT 0;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Trend" text NOT NULL DEFAULT 'stable';
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "Specification" text;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "IsLiveAutoUpdated" boolean NOT NULL DEFAULT true;
                ALTER TABLE "MarketPrices" ADD COLUMN IF NOT EXISTS "CityRatesJson" text;
                """);

            // Create FAQItems table if it doesn't exist in Postgres (e.g. Linux Production server)
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "FAQItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "QuestionAr" text NOT NULL,
                    "AnswerAr" text NOT NULL,
                    "QuestionEn" text,
                    "AnswerEn" text,
                    "PageTarget" text NOT NULL DEFAULT 'calculator',
                    "DisplayOrder" integer NOT NULL DEFAULT 0,
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    "UpdatedAt" timestamp with time zone
                );
                """);

            // Ensure all FAQItems columns exist
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "QuestionAr" text NOT NULL DEFAULT '';
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "AnswerAr" text NOT NULL DEFAULT '';
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "QuestionEn" text;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "AnswerEn" text;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "PageTarget" text NOT NULL DEFAULT 'calculator';
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "DisplayOrder" integer NOT NULL DEFAULT 0;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT true;
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());
                ALTER TABLE "FAQItems" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone;
                """);

            // Create SEOMetadata table if it doesn't exist in Postgres
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "SEOMetadata" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "PageName" text NOT NULL,
                    "PageTitle" text,
                    "MetaDescription" text,
                    "MetaKeywords" text,
                    "PageUrl" text,
                    "PageOrder" integer,
                    "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now())
                );
                """);

            // Ensure all SEOMetadata columns exist
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageName" text NOT NULL DEFAULT '';
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageTitle" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "MetaDescription" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "MetaKeywords" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageUrl" text;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "PageOrder" integer;
                ALTER TABLE "SEOMetadata" ADD COLUMN IF NOT EXISTS "LastUpdated" timestamp with time zone NOT NULL DEFAULT (now());
                """);

            // Seed default MarketPrices if table is empty
            await db.Database.ExecuteSqlRawAsync(
                """
                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'حديد تسليح مشوه (Grade 60) - حديد الأردن والوطنية', 515.00, 'طن', 'JOD', now(), 'مصانع الصلب الأردنية المعتمدة', 'Jordan & National Steel Rebar (Grade 60)', 'Steel', 518.00, 725.00, -0.58, 'down', 'عالي المقاومة ومطابق للمواصفة القياسية الأردنية JS 29:2018 وكود نقابة المهندسين.', true
                WHERE NOT EXISTS (SELECT 1 FROM "MarketPrices" LIMIT 1);

                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'إسمنت بورتلاندي بوزولاني وبورتلاندي عادي (لافارج والقطرانة)', 88.00, 'طن', 'JOD', now(), 'شركات الإسمنت الأردنية الرسمية', 'Lafarge & Qatrana Portland Cement CEM I', 'Cement', 88.00, 124.00, 0.0, 'stable', 'أكياس 50 كغم ومطابق للمواصفة الأردنية JS 30-1 لقوة التحمل والمتانة الإنشائية.', true
                WHERE (SELECT COUNT(*) FROM "MarketPrices") = 1;

                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'خرسانة جاهزة B250 / B300 (المناصير ولافارج للبيتون)', 43.50, 'متر مكعب', 'JOD', now(), 'محطات ومصانع الخرسانة الجاهزة الكبرى', 'Ready-Mix Concrete B250/B300 (Manaseer / Lafarge)', 'Concrete', 43.50, 61.35, 0.0, 'stable', 'شاملة المضخة والفحص المخبري لمقاومة الكسر بعد 28 يوماً.', true
                WHERE (SELECT COUNT(*) FROM "MarketPrices") = 2;

                INSERT INTO "MarketPrices" ("MaterialName", "Price", "UnitOfMeasure", "Currency", "LastUpdated", "Source", "MaterialNameEn", "MaterialCategory", "PreviousPrice", "GlobalPriceUsd", "ChangePercent", "Trend", "Specification", "IsLiveAutoUpdated")
                SELECT 'طوب إسمنتي آلي مفرغ وهوردي (10 / 15 / 20 سم)', 0.36, 'حبة', 'JOD', now(), 'مصانع الطوب الآلية المعتمدة', 'Automated Hollow & Rib Concrete Blocks', 'Blocks', 0.36, 0.51, 0.0, 'stable', 'معالج بالبخار ومطابق للأبعاد الهندسية وعزل الصوت والحرارة.', true
                WHERE (SELECT COUNT(*) FROM "MarketPrices") = 3;
                """);

            // Seed default FAQs if table is empty
            await db.Database.ExecuteSqlRawAsync(
                """
                INSERT INTO "FAQItems" ("QuestionAr", "AnswerAr", "QuestionEn", "AnswerEn", "PageTarget", "DisplayOrder", "IsActive", "CreatedAt")
                SELECT 
                    'كيف يتم احتساب كمية حديد التسليح للمشروع؟',
                    'يتم احتساب كمية الحديد بناءً على الكودات الهندسية الأردنية المعتمدة للمباني السكنية والتجارية بمعدل يتراوح بين 38 إلى 45 كغم لكل متر مربع مسطح من إجمالي مساحة البناء (Built-up Area)، وتزداد النسبة تلقائياً في حال اختيار أساسات اللبشة (Raft) أو الاستخدام التجاري.',
                    'How is the rebar quantity calculated for the project?',
                    'Rebar quantity is estimated based on Jordanian National Building Codes, averaging 38 to 45 kg per m² of total built-up area for standard residential rib slabs and isolated footings, automatically scaled for commercial structures and raft foundations.',
                    'calculator', 1, true, now()
                WHERE NOT EXISTS (SELECT 1 FROM "FAQItems" LIMIT 1);
                """);

            Log.Information("Database tables (Delivery, FAQItems, MarketPrices, SEOMetadata) verified/created successfully via raw SQL.");
        }
        catch (Exception sqlEx)
        {
            Log.Warning(sqlEx, "Failed to apply raw SQL schema changes.");
        }
    }

    #endregion

    #region Data Seeding

    /// <summary>
    /// Seeds initial data based on environment
    /// </summary>
    private static async Task SeedDataAsync(this WebApplication app)
    {
        // Only seed identity data in Development
        if (app.Environment.IsDevelopment())
        {
            await app.SeedIdentityDataAsync();
            Log.Information("Development identity data seeded");
        }
        else
        {
            // In Production, the /Setup page handles first-run admin creation
            Log.Information("Production mode: skipping automatic data seeding. Use /Setup for initial admin creation.");
        }
    }

    #endregion
}
