using Bolcko.Domain.Entities.User;
using Bolcko.Domain.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Bolcko.Web.App.Extensions
{
    public static class IdentityDataSeeder
    {
        public static async Task SeedIdentityDataAsync(this IApplicationBuilder app)
        {
            using var scope = app.ApplicationServices.CreateScope();
            var db = scope.ServiceProvider.GetRequiredService<Blocko.Persistence.BlockoDbContext>();
            try
            {
                await db.Database.ExecuteSqlRawAsync(@"
                    CREATE TABLE IF NOT EXISTS ""DeliveryProviderConfigs"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""ProviderName"" text NOT NULL,
                        ""ProviderKey"" text NOT NULL,
                        ""BaseUrl"" text NOT NULL,
                        ""CompanyId"" text NOT NULL,
                        ""ApiEmail"" text NOT NULL,
                        ""ApiPassword"" text NOT NULL,
                        ""WebhookSecret"" text NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NULL,
                        CONSTRAINT ""PK_DeliveryProviderConfigs"" PRIMARY KEY (""Id"")
                    );

                    CREATE TABLE IF NOT EXISTS ""OrderShipmentMappings"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""OrderId"" integer NOT NULL,
                        ""ProviderKey"" text NOT NULL,
                        ""ExternalPackageId"" text NULL,
                        ""Barcode"" text NULL,
                        ""CodBarcode"" text NULL,
                        ""AwbPdfUrl"" text NULL,
                        ""CurrentStatus"" text NULL,
                        ""ArabicStatus"" text NULL,
                        ""CodAmount"" double precision NOT NULL,
                        ""AssignedDriverName"" text NULL,
                        ""AssignedDriverPhone"" text NULL,
                        ""RawWebhookPayload"" text NULL,
                        ""DispatchedAt"" timestamp with time zone NOT NULL,
                        ""LastStatusUpdatedAt"" timestamp with time zone NULL,
                        CONSTRAINT ""PK_OrderShipmentMappings"" PRIMARY KEY (""Id"")
                    );

                    ALTER TABLE ""DeliveryProviderConfigs"" ADD COLUMN IF NOT EXISTS ""OutboundWebhookUrl"" text NULL;
                    ALTER TABLE ""DeliveryProviderConfigs"" ADD COLUMN IF NOT EXISTS ""CustomHeadersJson"" text NULL;
                    ALTER TABLE ""DeliveryProviderConfigs"" ADD COLUMN IF NOT EXISTS ""CustomPayloadMappingJson"" text NULL;
                    ALTER TABLE ""Addresses"" ADD COLUMN IF NOT EXISTS ""Latitude"" double precision NULL;
                    ALTER TABLE ""Addresses"" ADD COLUMN IF NOT EXISTS ""Longitude"" double precision NULL;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""IsOversized"" boolean NOT NULL DEFAULT false;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""CommercialRegistrationDocUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""VocationalLicenseDocUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""TaxCertificateDocUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""QualityCertificatesDocUrl"" text NULL;
                ");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("PostgreSQL Direct Seed Error: " + ex.Message);
            }

            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<User>>();
            var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole<int>>>();

            // 1. Seed Roles & Sync AppPermissions
            string[] roles = { "SuperAdmin", "Admin", "DashboardUser", "Customer", "DeliveryDriver", "DeliveryCompanyUser", "Vendor", "Contractor", "Investor" };
            foreach (var role in roles)
            {
                if (!await roleManager.RoleExistsAsync(role))
                {
                    await roleManager.CreateAsync(new IdentityRole<int> { Name = role });
                }
            }

            // Sync All System AppPermissions to SuperAdmin and Admin Roles
            var privilegedRoles = new[] { "SuperAdmin", "Admin" };
            var allPermissionKeys = Bolcko.Domain.Common.AppPermissions.GetAllPermissionGroups()
                .SelectMany(g => g.Permissions)
                .Select(p => p.Key)
                .ToList();

            foreach (var roleName in privilegedRoles)
            {
                var roleEntity = await roleManager.FindByNameAsync(roleName);
                if (roleEntity != null)
                {
                    var existingClaims = await roleManager.GetClaimsAsync(roleEntity);
                    var existingPermissionValues = existingClaims.Where(c => c.Type == "Permission").Select(c => c.Value).ToHashSet();

                    foreach (var permKey in allPermissionKeys)
                    {
                        if (!existingPermissionValues.Contains(permKey))
                        {
                            await roleManager.AddClaimAsync(roleEntity, new System.Security.Claims.Claim("Permission", permKey));
                        }
                    }
                }
            }

            // 2. Seed First Super Admin
            var adminEmail = "admin@blocko.com";
            var adminUser = await userManager.FindByEmailAsync(adminEmail);

            if (adminUser == null)
            {
                var newAdmin = new User
                {
                    UserName = adminEmail,
                    Email = adminEmail,
                    FirstName = "Super",
                    LastName = "Admin",
                    UserType = UserType.Admin,
                    EmailConfirmed = true,
                    MustChangePassword = false,
                    RegistrationDate = DateTime.UtcNow
                };

                var result = await userManager.CreateAsync(newAdmin, "BolckoAdmin@2026!");
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(newAdmin, "SuperAdmin");
                    await userManager.AddToRoleAsync(newAdmin, "Admin");
                }
            }
            else
            {
                if (!await userManager.IsInRoleAsync(adminUser, "SuperAdmin"))
                {
                    await userManager.AddToRoleAsync(adminUser, "SuperAdmin");
                }
                if (!await userManager.IsInRoleAsync(adminUser, "Admin"))
                {
                    await userManager.AddToRoleAsync(adminUser, "Admin");
                }
            }

            // 3. Seed QA Test Account (Shop customer login)
            var qaEmail = "Qa@blocko.com";
            var qaUser = await userManager.FindByEmailAsync(qaEmail);

            if (qaUser == null)
            {
                var newQaUser = new User
                {
                    UserName = qaEmail,
                    Email = qaEmail,
                    FirstName = "QA",
                    LastName = "Tester",
                    UserType = UserType.Customer,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };

                var qaResult = await userManager.CreateAsync(newQaUser, "Qa@blocko@123");
                if (qaResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newQaUser, "Customer");
                }
            }

            // 4. Seed Investor Account
            var investorEmail = "investor@blocko.com";
            var investorUser = await userManager.FindByEmailAsync(investorEmail);
            if (investorUser == null)
            {
                var newInv = new User
                {
                    UserName = investorEmail,
                    Email = investorEmail,
                    FirstName = "م. طارق",
                    LastName = "المجالي",
                    CompanyName = "صندوق النماء للاستثمار التمويلي",
                    UserType = UserType.Investor,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };
                var invResult = await userManager.CreateAsync(newInv, "Investor@2026!");
                if (invResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newInv, "Investor");
                }
            }

            // 5. Seed Contractor Account
            var contractorEmail = "contractor@blocko.com";
            var contractorUser = await userManager.FindByEmailAsync(contractorEmail);
            if (contractorUser == null)
            {
                var newCon = new User
                {
                    UserName = contractorEmail,
                    Email = contractorEmail,
                    FirstName = "م. عمر",
                    LastName = "الخالدي",
                    CompanyName = "شركة الأفق للمقاولات العامة",
                    UserType = UserType.Contractor,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };
                var conResult = await userManager.CreateAsync(newCon, "Contractor@2026!");
                if (conResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newCon, "Contractor");
                }
            }

            // 6. Seed Market Prices
            var dbContext = scope.ServiceProvider.GetRequiredService<Blocko.Persistence.BlockoDbContext>();
            if (!dbContext.MarketPrices.Any())
            {
                dbContext.MarketPrices.AddRange(
                    new Bolcko.Domain.Entities.Catalog.MarketPrice 
                    { 
                        MaterialName = "حديد تسليح سابك", 
                        Price = 610.50m, 
                        Currency = "د.أ", 
                        UnitOfMeasure = "طن", 
                        LastUpdated = DateTime.UtcNow 
                    },
                    new Bolcko.Domain.Entities.Catalog.MarketPrice 
                    { 
                        MaterialName = "أسمنت الراجحي", 
                        Price = 75.00m, 
                        Currency = "د.أ", 
                        UnitOfMeasure = "طن", 
                        LastUpdated = DateTime.UtcNow 
                    },
                    new Bolcko.Domain.Entities.Catalog.MarketPrice 
                    { 
                        MaterialName = "خرسانة جاهزة", 
                        Price = 45.00m, 
                        Currency = "د.أ", 
                        UnitOfMeasure = "متر مكعب", 
                        LastUpdated = DateTime.UtcNow 
                    }
                );
                await dbContext.SaveChangesAsync();
            }
        }
    }
}
