using Bolcko.Domain.Entities.User;
using Bolcko.Domain.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Bolcko.Web.App.Extensions
{
    public static class IdentityDataSeeder
    {
        public static async Task SeedIdentityDataAsync(this IApplicationBuilder app)
        {
            using var scope = app.ApplicationServices.CreateScope();
            var db = scope.ServiceProvider.GetRequiredService<Blocko.Persistence.BlockoDbContext>();
            try
            {
                await db.Database.ExecuteSqlRawAsync(@"
                    CREATE TABLE IF NOT EXISTS ""DeliveryProviderConfigs"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""ProviderName"" text NOT NULL,
                        ""ProviderKey"" text NOT NULL,
                        ""BaseUrl"" text NOT NULL,
                        ""CompanyId"" text NOT NULL,
                        ""ApiEmail"" text NOT NULL,
                        ""ApiPassword"" text NOT NULL,
                        ""WebhookSecret"" text NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NULL,
                        CONSTRAINT ""PK_DeliveryProviderConfigs"" PRIMARY KEY (""Id"")
                    );

                    CREATE TABLE IF NOT EXISTS ""OrderShipmentMappings"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                        ""OrderId"" integer NOT NULL,
                        ""ProviderKey"" text NOT NULL,
                        ""ExternalPackageId"" text NULL,
                        ""Barcode"" text NULL,
                        ""CodBarcode"" text NULL,
                        ""AwbPdfUrl"" text NULL,
                        ""CurrentStatus"" text NULL,
                        ""ArabicStatus"" text NULL,
                        ""CodAmount"" double precision NOT NULL,
                        ""AssignedDriverName"" text NULL,
                        ""AssignedDriverPhone"" text NULL,
                        ""RawWebhookPayload"" text NULL,
                        ""DispatchedAt"" timestamp with time zone NOT NULL,
                        ""LastStatusUpdatedAt"" timestamp with time zone NULL,
                        CONSTRAINT ""PK_OrderShipmentMappings"" PRIMARY KEY (""Id"")
                    );

                    ALTER TABLE ""DeliveryProviderConfigs"" ADD COLUMN IF NOT EXISTS ""OutboundWebhookUrl"" text NULL;
                    ALTER TABLE ""DeliveryProviderConfigs"" ADD COLUMN IF NOT EXISTS ""CustomHeadersJson"" text NULL;
                    ALTER TABLE ""DeliveryProviderConfigs"" ADD COLUMN IF NOT EXISTS ""CustomPayloadMappingJson"" text NULL;
                    ALTER TABLE ""Addresses"" ADD COLUMN IF NOT EXISTS ""Latitude"" double precision NULL;
                    ALTER TABLE ""Addresses"" ADD COLUMN IF NOT EXISTS ""Longitude"" double precision NULL;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""IsOversized"" boolean NOT NULL DEFAULT false;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""SupplierKey"" text NULL DEFAULT 'qannas';
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""ExternalSupplierVariantId"" integer NULL;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""TechnicalDatasheetUrl"" text NULL;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""MillTestCertificateUrl"" text NULL;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""RssApprovalUrl"" text NULL;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""IsExclusivePatented"" boolean NOT NULL DEFAULT false;
                    ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""SearchRankingScore"" double precision NOT NULL DEFAULT 1.0;

                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""CommercialRegistrationDocUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""VocationalLicenseDocUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""TaxCertificateDocUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""QualityCertificatesDocUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""MerchantType"" integer NOT NULL DEFAULT 1;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""SubscriptionTier"" text NOT NULL DEFAULT 'Gold';
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""IsGoldVerified"" boolean NOT NULL DEFAULT true;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""IsExclusiveAgent"" boolean NOT NULL DEFAULT false;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""Latitude"" double precision NOT NULL DEFAULT 31.9392;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""Longitude"" double precision NOT NULL DEFAULT 35.9189;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""WarehouseLocationName"" text NOT NULL DEFAULT 'مستودعات رأس العين - عمان المركزية';
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""TechnicalDatasheetUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""MillTestCertificateUrl"" text NULL;
                    ALTER TABLE ""VendorProfiles"" ADD COLUMN IF NOT EXISTS ""RssApprovalUrl"" text NULL;

                    ALTER TABLE ""FinancingTenders"" ADD COLUMN IF NOT EXISTS ""DeliveryOtpCode"" text NULL;
                    ALTER TABLE ""FinancingTenders"" ADD COLUMN IF NOT EXISTS ""DeliveryOtpExpiresAt"" timestamp with time zone NULL;
                    ALTER TABLE ""FinancingTenders"" ADD COLUMN IF NOT EXISTS ""EscrowStatus"" text NOT NULL DEFAULT 'HeldInEscrow';
                    ALTER TABLE ""FinancingTenders"" ADD COLUMN IF NOT EXISTS ""EscrowReleasedAt"" timestamp with time zone NULL;
                    ALTER TABLE ""FinancingTenders"" ADD COLUMN IF NOT EXISTS ""EscrowReleaseTransactionReference"" text NULL;
                    ALTER TABLE ""FinancingTenders"" ADD COLUMN IF NOT EXISTS ""MurabahaContractStatus"" text NOT NULL DEFAULT 'Draft';
                    ALTER TABLE ""FinancingTenders"" ADD COLUMN IF NOT EXISTS ""InstallmentScheduleJson"" text NULL;

                    -- Catalog Attribution Migration (MGR-01 / QT1-137)
                    UPDATE ""Products""
                    SET ""SupplierId"" = 1,
                        ""SupplierKey"" = 'qannas',
                        ""SearchRankingScore"" = 1.5
                    WHERE ""SupplierId"" IS NULL OR ""SupplierKey"" IS NULL OR ""SupplierKey"" = '';
                ");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("PostgreSQL Direct Seed Error: " + ex.Message);
            }

            var userManager = scope.ServiceProvider.GetRequiredService<UserManager<User>>();
            var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole<int>>>();

            // 1. Seed Roles & Sync AppPermissions
            string[] roles = { "SuperAdmin", "Admin", "DashboardUser", "Customer", "DeliveryDriver", "DeliveryCompanyUser", "Vendor", "Contractor", "Investor" };
            foreach (var role in roles)
            {
                if (!await roleManager.RoleExistsAsync(role))
                {
                    await roleManager.CreateAsync(new IdentityRole<int> { Name = role });
                }
            }

            // Sync All System AppPermissions to SuperAdmin and Admin Roles
            var privilegedRoles = new[] { "SuperAdmin", "Admin" };
            var allPermissionKeys = Bolcko.Domain.Common.AppPermissions.GetAllPermissionGroups()
                .SelectMany(g => g.Permissions)
                .Select(p => p.Key)
                .ToList();

            foreach (var roleName in privilegedRoles)
            {
                var roleEntity = await roleManager.FindByNameAsync(roleName);
                if (roleEntity != null)
                {
                    var existingClaims = await roleManager.GetClaimsAsync(roleEntity);
                    var existingPermissionValues = existingClaims.Where(c => c.Type == "Permission").Select(c => c.Value).ToHashSet();

                    foreach (var permKey in allPermissionKeys)
                    {
                        if (!existingPermissionValues.Contains(permKey))
                        {
                            await roleManager.AddClaimAsync(roleEntity, new System.Security.Claims.Claim("Permission", permKey));
                        }
                    }
                }
            }

            // 2. Seed First Super Admin
            var adminEmail = "admin@blocko.com";
            var adminUser = await userManager.FindByEmailAsync(adminEmail);

            if (adminUser == null)
            {
                var newAdmin = new User
                {
                    UserName = adminEmail,
                    Email = adminEmail,
                    FirstName = "Super",
                    LastName = "Admin",
                    UserType = UserType.Admin,
                    EmailConfirmed = true,
                    MustChangePassword = false,
                    RegistrationDate = DateTime.UtcNow
                };

                var result = await userManager.CreateAsync(newAdmin, "BolckoAdmin@2026!");
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(newAdmin, "SuperAdmin");
                    await userManager.AddToRoleAsync(newAdmin, "Admin");
                }
            }
            else
            {
                if (!await userManager.IsInRoleAsync(adminUser, "SuperAdmin"))
                {
                    await userManager.AddToRoleAsync(adminUser, "SuperAdmin");
                }
                if (!await userManager.IsInRoleAsync(adminUser, "Admin"))
                {
                    await userManager.AddToRoleAsync(adminUser, "Admin");
                }
            }

            // 3. Seed QA Test Account (Shop customer login)
            var qaEmail = "Qa@blocko.com";
            var qaUser = await userManager.FindByEmailAsync(qaEmail);

            if (qaUser == null)
            {
                var newQaUser = new User
                {
                    UserName = qaEmail,
                    Email = qaEmail,
                    FirstName = "QA",
                    LastName = "Tester",
                    UserType = UserType.Customer,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };

                var qaResult = await userManager.CreateAsync(newQaUser, "Qa@blocko@123");
                if (qaResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newQaUser, "Customer");
                }
            }

            // 4. Seed Investor Account
            var investorEmail = "investor@blocko.com";
            var investorUser = await userManager.FindByEmailAsync(investorEmail);
            if (investorUser == null)
            {
                var newInv = new User
                {
                    UserName = investorEmail,
                    Email = investorEmail,
                    FirstName = "م. طارق",
                    LastName = "المجالي",
                    CompanyName = "صندوق النماء للاستثمار التمويلي",
                    UserType = UserType.Investor,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };
                var invResult = await userManager.CreateAsync(newInv, "Investor@2026!");
                if (invResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newInv, "Investor");
                }
            }

            // 5. Seed Contractor Account
            var contractorEmail = "contractor@blocko.com";
            var contractorUser = await userManager.FindByEmailAsync(contractorEmail);
            if (contractorUser == null)
            {
                var newCon = new User
                {
                    UserName = contractorEmail,
                    Email = contractorEmail,
                    FirstName = "م. عمر",
                    LastName = "الخالدي",
                    CompanyName = "شركة الأفق للمقاولات العامة",
                    UserType = UserType.Contractor,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };
                var conResult = await userManager.CreateAsync(newCon, "Contractor@2026!");
                if (conResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newCon, "Contractor");
                }
            }

            // 5b. Seed Freelance Heavy Hauler Driver (LOG-01 / LOG-03)
            var driverEmail = "driver@blocko.com";
            var driverUser = await userManager.FindByEmailAsync(driverEmail);
            if (driverUser == null)
            {
                var newDriverUser = new User
                {
                    UserName = driverEmail,
                    Email = driverEmail,
                    FirstName = "أحمد",
                    LastName = "الخالدي",
                    PhoneNumber = "0791234567",
                    UserType = UserType.DeliveryDriver,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };

                var dResult = await userManager.CreateAsync(newDriverUser, "Driver@2026!");
                if (dResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newDriverUser, "DeliveryDriver");

                    var driverEntity = new Bolcko.Domain.Entities.Delivery.DeliveryDriver
                    {
                        UserId = newDriverUser.Id,
                        VehicleType = "تريلا قلاب 30 طن",
                        VehiclePlateNumber = "12-38491",
                        LicenseNumber = "LTRC-DRV-001",
                        NationalId = "9901020304",
                        HeavyLicenseCategory = "الفئة السادسة - قاطرة ومقطورة",
                        CapacityTons = 30,
                        CoveredGovernorate = "عمان، الزرقاء، البلقاء، إربد",
                        CliqAlias = "BLOCKO_DRIVER_CLI",
                        IsAvailable = true,
                        IsApproved = true,
                        ApprovedAt = DateTime.UtcNow,
                        AverageRating = 4.9m,
                        TotalRatings = 18,
                        TotalDeliveredOrders = 42
                    };
                    await db.DeliveryDrivers.AddAsync(driverEntity);
                    await db.SaveChangesAsync();
                }
            }

            // 5c. Seed 3PL Fleet Carrier Company (LOG-01 / LOG-04)
            var carrierEmail = "carrier@blocko.com";
            var carrierUser = await userManager.FindByEmailAsync(carrierEmail);
            if (carrierUser == null)
            {
                var newCarrierUser = new User
                {
                    UserName = carrierEmail,
                    Email = carrierEmail,
                    FirstName = "محمود",
                    LastName = "الزعبي",
                    CompanyName = "شركة أسطول الأردن للنقل اللوجستي ذ.م.م",
                    PhoneNumber = "0788765432",
                    UserType = UserType.DeliveryCompanyUser,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };

                var cResult = await userManager.CreateAsync(newCarrierUser, "Carrier@2026!");
                if (cResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newCarrierUser, "DeliveryCompanyUser");

                    var companyEntity = new Bolcko.Domain.Entities.Delivery.DeliveryCompany
                    {
                        Name = "شركة أسطول الأردن للنقل اللوجستي ذ.م.م",
                        Email = carrierEmail,
                        PhoneNumber = "0788765432",
                        CommercialRegister = "100294819",
                        TaxId = "78912345",
                        TransportCommissionLicense = "LTRC-CO-2026-99",
                        CliqAlias = "JORDAN_FLEET_3PL",
                        TotalTrucksCount = 8,
                        BaseDeliveryRate = 25.00m,
                        IsActive = true,
                        IsApproved = true,
                        SupportsOversized = true,
                        IsApiIntegration = true,
                        ManagerUserId = newCarrierUser.Id.ToString()
                    };
                    await db.DeliveryCompanies.AddAsync(companyEntity);
                    await db.SaveChangesAsync();
                }
            }

            // 6. Seed Market Prices
            var dbContext = scope.ServiceProvider.GetRequiredService<Blocko.Persistence.BlockoDbContext>();
            if (!dbContext.MarketPrices.Any())
            {
                dbContext.MarketPrices.AddRange(
                    new Bolcko.Domain.Entities.Catalog.MarketPrice 
                    { 
                        MaterialName = "حديد تسليح سابك", 
                        Price = 610.50m, 
                        Currency = "د.أ", 
                        UnitOfMeasure = "طن", 
                        LastUpdated = DateTime.UtcNow 
                    },
                    new Bolcko.Domain.Entities.Catalog.MarketPrice 
                    { 
                        MaterialName = "أسمنت الراجحي", 
                        Price = 75.00m, 
                        Currency = "د.أ", 
                        UnitOfMeasure = "طن", 
                        LastUpdated = DateTime.UtcNow 
                    },
                    new Bolcko.Domain.Entities.Catalog.MarketPrice 
                    { 
                        MaterialName = "خرسانة جاهزة", 
                        Price = 45.00m, 
                        Currency = "د.أ", 
                        UnitOfMeasure = "متر مكعب", 
                        LastUpdated = DateTime.UtcNow 
                    }
                );
                await dbContext.SaveChangesAsync();
            }

            // 7. Seed Al-Qannas Gold Benchmark Supplier (User 13 / MGR-01)
            var vendorEmail = "cleanrjo@gmail.com";
            var vendorUser = await userManager.FindByEmailAsync(vendorEmail);
            if (vendorUser == null)
            {
                var newVendor = new User
                {
                    UserName = vendorEmail,
                    Email = vendorEmail,
                    PhoneNumber = "0782023800",
                    FirstName = "مجموعة القناص",
                    LastName = "لمواد البناء",
                    CompanyName = "شركة القناص لتجارة مواد البناء ذ.م.م",
                    UserType = UserType.Vendor,
                    EmailConfirmed = true,
                    RegistrationDate = DateTime.UtcNow
                };
                var vResult = await userManager.CreateAsync(newVendor, "Qannas@2026!");
                if (vResult.Succeeded)
                {
                    await userManager.AddToRoleAsync(newVendor, "Vendor");
                    vendorUser = newVendor;
                }
            }
            else
            {
                if (!await userManager.IsInRoleAsync(vendorUser, "Vendor"))
                {
                    await userManager.AddToRoleAsync(vendorUser, "Vendor");
                }
            }

            if (vendorUser != null)
            {
                var vProfile = await dbContext.VendorProfiles.FirstOrDefaultAsync(v => v.UserId == vendorUser.Id || v.Id == 1);
                if (vProfile == null)
                {
                    vProfile = new Bolcko.Domain.Entities.Catalog.VendorProfile
                    {
                        UserId = vendorUser.Id,
                        CompanyNameAr = "مجموعة القنّاص لمواد البناء",
                        CompanyNameEn = "Al-Qannas Building Materials",
                        CommercialRegistrationNo = "200194827",
                        TaxNumber = "10928374",
                        City = "عمان",
                        AddressText = "رأس العين - المنطقة الصناعية",
                        Phone = "0782023800",
                        WhatsApp = "962782023800",
                        ContactPersonName = "إدارة المبيعات والتوريد",
                        SuppliedCategories = "Stone,Steel,ReadyMix,Insulation,Plumbing,BuildingMaterials",
                        Status = "Active",
                        CommissionRatePercentage = 1.5m,
                        Rating = 4.9,
                        SubscriptionTier = "Gold",
                        IsGoldVerified = true,
                        MerchantType = Bolcko.Domain.Enums.MerchantType.Manufacturer,
                        Latitude = 31.9392,
                        Longitude = 35.9189,
                        WarehouseLocationName = "مستودعات رأس العين - عمان المركزية",
                        RegisteredAt = DateTime.UtcNow,
                        VerifiedAt = DateTime.UtcNow
                    };
                    await dbContext.VendorProfiles.AddAsync(vProfile);
                }
                else
                {
                    vProfile.SubscriptionTier = "Gold";
                    vProfile.CommissionRatePercentage = 1.5m;
                    vProfile.IsGoldVerified = true;
                    vProfile.MerchantType = Bolcko.Domain.Enums.MerchantType.Manufacturer;
                    vProfile.Latitude = 31.9392;
                    vProfile.Longitude = 35.9189;
                    vProfile.WarehouseLocationName = "مستودعات رأس العين - عمان المركزية";
                    dbContext.VendorProfiles.Update(vProfile);
                }
                await dbContext.SaveChangesAsync();
            }
        }
    }
}
