namespace Bolcko.Domain.Entities.Product.DTOs
{
    public class ProductImportDto
    {
        /// <summary>SKU can come from the sheet (كود المنتج) or be auto-generated by the system.</summary>
        public string Sku { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        /// <summary>English product name — mapped from "Product Name (English)" column.</summary>
        public string? NameEn { get; set; }

        public string? Description { get; set; }

        /// <summary>English description — mapped from "Description (English)" column.</summary>
        public string? DescriptionEn { get; set; }

        public string CategoryName { get; set; } = string.Empty;
        public decimal RetailPrice { get; set; }
        public string UnitOfMeasure { get; set; } = string.Empty;
        public int StockQuantity { get; set; }
        public decimal? Weight { get; set; }
        public string? Dimensions { get; set; }
        public bool BulkPricingAvailable { get; set; }
        public string Status { get; set; } = "Active";

        public string? Brand { get; set; }
        public string? CountryOfOrigin { get; set; }
        public bool IsOversized { get; set; }

        // Product Variant Attributes (Optional, for child variant rows or variant-specific attributes)
        public string? ParentSku { get; set; }
        public string? VariantSku { get; set; }
        public string? Size { get; set; }
        public string? Color { get; set; }
        public string? PackagingUnit { get; set; }
        public decimal? VariantPrice { get; set; }
        public int? VariantStock { get; set; }
        public string? VariantImageUrl { get; set; }

        // Image extracted from Excel embedded picture or URL
        public byte[]? ImageData { get; set; }
        public string? ImageMimeType { get; set; }
        public string? ImageExtension { get; set; }
        
        public List<(byte[] Data, string Ext, string MimeType)> AdditionalImages { get; set; } = new();

        // Category Metadata from sheet
        public string? CategoryIcon { get; set; }
        public string? ParentCategoryName { get; set; }
        public string? MicroCategoryName { get; set; }

        // Image from JSON base64 string or direct URL
        public string? ImageBase64 { get; set; }

        // SEO Metadata from sheet
        public string? MetaTitle { get; set; }
        public string? MetaDescription { get; set; }
        public string? MetaKeywords { get; set; }
    }
}
