namespace Bolcko.Domain.Entities.Product.DTOs
{
    public class ProductImportDto
    {
        /// <summary>SKU is auto-generated by the system — not required from the file.</summary>
        public string Sku { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
        public string CategoryName { get; set; } = string.Empty;
        public decimal RetailPrice { get; set; }
        public string UnitOfMeasure { get; set; } = string.Empty;
        public int StockQuantity { get; set; }
        public decimal? Weight { get; set; }
        public string? Dimensions { get; set; }
        public bool BulkPricingAvailable { get; set; }
        public string Status { get; set; } = "Active";

        public string? Brand { get; set; }
        public string? CountryOfOrigin { get; set; }

        // Image extracted from Excel embedded picture
        public byte[]? ImageData { get; set; }
        public string? ImageMimeType { get; set; }
        public string? ImageExtension { get; set; }
        
        public List<(byte[] Data, string Ext, string MimeType)> AdditionalImages { get; set; } = new();

        // Category Metadata from sheet
        public string? CategoryIcon { get; set; }
        public string? ParentCategoryName { get; set; }

        // Image from JSON base64 string (e.g. "data:image/jpeg;base64,...")
        public string? ImageBase64 { get; set; }
    }
}
